name: Issues Workflow
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Get Event details
              run: |
                     echo "${{ toJSON(github.event) }}"
              
           
